# https://github.com/vektra/mockery
with-expecter: true
packages:
  github.com/jackpal/gateway:
    interfaces:
      interfaceGetter:
        config:
          mockName: "{{.Mock}}{{.InterfaceName}}"
          filename: "mock_{{.InterfaceName}}_test.go"
          inpackage: true
          dir: "{{.InterfaceDir}}"
